const data = {
    "clothes": [
        'underwear',
        'socks/stockings',
        'undershirts/bras',
        'sleepwear',
        'shirts',
        'dress shirts',
        'casual shirts',
        'jeans',
        'pants',
        'shorts',
        'dresses',
        'skirts',
        'sweaters/sweatshirts',
        'formalwear',
        'swimsuits/cover-ups',
        'coats/jackets/rainwear',
        'hats',
        'gloves',
        'scarves',
        'umbrella',
        'laundry kit',
        'laundry bag',
        'leisure shoes',
        'hiking shoes/athletic shoes',
        'walking shoes',
        'dress shoes',
        'sandals/flip flops',
        'belts',
        'ties',
        'jewelry (if valuable, put in carry-on)',
        'purses',
        'collapsible totes',
        'under clothing document holders'
    ],
    "toiletries": [
        'toothbrush',
        'toothpaste',
        'dentalFloss',
        'soap',
        'deodorant',
        'shampoo/conditioner',
        'brush/comb',
        'hairstyling tools',
        'face cleanser',
        'face moisturizer/tonic/serum, etc',
        'sunscreen',
        'moisturizer',
        'contact lenses/contact solution',
        'shaving kit',
        'make-up/make-up remover',
        'feminine hygiene products',
        'birth control',
        'nail file/nail clippers',
        'tweezers',
        'hand sanitizer',
        'bandages',
        'first aid ointment',
        'insect repellent',
        'medications',
        'pain relievers',
        'vitamins'
    ],
    "misc": [
        'mobilePhone',
        'laptop/tablet/game device',
        'device chargers',
        'plug adaptor',
        'binoculars',
        'listof medications',
        'emergency contacts',
        'credit card contacts/bank contacts',
        'passport copy/credit card copy'
    ],
    "carryon": [
        'books/eBooks',
        'earbuds/headphones',
        'shawl/travel blanket',
        'travel pillow',
        'ear plugs/eye mask',
        'tissues',
        'lip balm',
        'change of clothes',
        'food/snacks/gum',
        'in-flight medications',
        'valuables',
        'camera/memory card',
        'passport/visa/id',
        'paper/pen',
        'cash',
        'cards: atm/credit',
        'insurance: health/travel',
        'itinerary',
        'maps/directions',
        'guidebook',
        'address book',
        'keys: house/car'
    ]
};

export default data;



